version: '{build}'
branches:
  only:
    - master
    - /^fidoroute-.*/
image:
  - Visual Studio 2017
environment:
  matrix:
    - generator: Visual Studio 15 2017
      cf: -T v141_xp
      pf: "msvc2017"
    - generator: Visual Studio 15 2017 Win64
      pf: "msvc2017"
build_script:
  - cmd: 
      cd C:\projects\fidoroute && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" %CF% && cmake --build . -- /P:Configuration=Release
  - cmd: cpack
  - ps:  gci *.7z | %{ rename-item –path $_.Fullname –Newname ( $_.basename +"-"+$Env:pf+$_.extension) }
artifacts:
  - path: build\*.7z
    name: dist
deploy:
  provider: GitHub
  artifact: dist
  auth_token: $(GITHUB_OAUTH_TOKEN)
  on:
    appveyor_repo_tag: true
